### ISSUE TITLE
 Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by PlayMa256** [PlayMa256/webpackx#3]
Testing with https://github.com/entria/entria-fullstack/blob/master/packages/server/scripts/updateSchema.js it breaks showing the following error.

<details>
<summary>Details</summary>

```
  [ ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
    at Compilation.reportDependencyErrorsAndWarnings (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1365:23)
    at hooks.finishModules.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1168:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/matheus/webpackx/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at CommonJsRequireContextDependency.getWarnings (/home/matheus/webpackx/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1360:24)
    at hooks.finishModules.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1168:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/matheus/webpackx/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11),
        ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
    at Compilation.reportDependencyErrorsAndWarnings (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1365:23)
    at hooks.finishModules.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1168:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/matheus/webpackx/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at CommonJsRequireContextDependency.getWarnings (/home/matheus/webpackx/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1360:24)
    at hooks.finishModules.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1168:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/matheus/webpackx/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11),
        ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
    at Compilation.reportDependencyErrorsAndWarnings (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1365:23)
    at hooks.finishModules.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1168:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/matheus/webpackx/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at CommonJsRequireContextDependency.getWarnings (/home/matheus/webpackx/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1360:24)
    at hooks.finishModules.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1168:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/matheus/webpackx/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11),
        ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
    at Compilation.reportDependencyErrorsAndWarnings (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1365:23)
    at hooks.finishModules.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1168:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/matheus/webpackx/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at RequireResolveContextDependency.getWarnings (/home/matheus/webpackx/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1360:24)
    at hooks.finishModules.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1168:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/matheus/webpackx/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/home/matheus/webpackx/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/home/matheus/webpackx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/home/matheus/webpackx/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11) ],
```

</details>

But, if using `webpack-node-externals` it works. The problem is, will it break?

**Comment by sibelius** [comment]
can we have a flag to add `webpack-node-external`?

or make it default?

**Comment by PlayMa256** [comment]
I suppose we can keep this as a flag, since adding this would require the `node_modules` folder to exist.
